# Generated by Django 5.2 on 2025-05-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingUser',
            fields=[
                ('ClimbingUserId', models.AutoField(primary_key=True, serialize=False)),
                ('ClimbingUserName', models.CharField(max_length=50)),
                ('ClimbingUserPassword', models.CharField(max_length=50)),
                ('ClimbingUserCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteId', models.AutoField(primary_key=True, serialize=False)),
                ('RouteLocationXAxis', models.PositiveIntegerField()),
                ('RouteLocationYAxis', models.PositiveIntegerField()),
                ('RouteCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('RouteDestroyedAt', models.DateTimeField()),
            ],
        ),
    ]
