# Generated by Django 5.2 on 2025-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='RouteColour',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default='RED', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='RouteGradeRange',
            field=models.CharField(choices=[('V0-V2', 'V0-V2'), ('V1-V3', 'V1-V3'), ('V2-V4', 'V2-V4')], default='V0-V2', max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteCreatedAt',
            field=models.DateTimeField(),
        ),
    ]
