# Generated by Django 5.2 on 2025-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0002_route_routecolour_route_routegraderange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='RouteCreatedAt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteDestroyedAt',
            field=models.DateField(),
        ),
    ]
