# Generated by Django 5.2 on 2025-05-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0003_alter_route_routecreatedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbingUserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateSent', models.DateField()),
                ('ClimbingUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.climbinguser')),
                ('RouteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbing_app.route')),
            ],
        ),
        migrations.AddField(
            model_name='climbinguser',
            name='RoutesClimbedByUser',
            field=models.ManyToManyField(through='climbing_app.ClimbingUserRoute', to='climbing_app.route'),
        ),
    ]
