# Generated by Django 5.2 on 2025-06-10 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0004_climbinguserroute_climbinguser_routesclimbedbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='RouteCreatedAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteDestroyedAt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
