# Generated by Django 5.2 on 2025-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0005_alter_route_routecreatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbinguser',
            name='IsStaffUser',
            field=models.BooleanField(default=False),
        ),
    ]
