# Generated by Django 5.2 on 2025-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0006_climbinguser_isstaffuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='RouteLocationXAxis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteLocationYAxis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
