# Generated by Django 5.2 on 2025-06-30 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0008_remove_route_routedestroyedat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbinguserroute',
            name='ClimbingUserId',
        ),
        migrations.RemoveField(
            model_name='climbinguserroute',
            name='RouteId',
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'permissions': [('can_delete_route', 'Can delete route'), ('can_add_route', 'Can add route')]},
        ),
        migrations.AddField(
            model_name='route',
            name='RoutesClimbedByUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClimbingUser',
        ),
        migrations.DeleteModel(
            name='ClimbingUserRoute',
        ),
    ]
