# Generated by Django 5.2 on 2025-07-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0009_remove_climbinguserroute_climbinguserid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'permissions': [('can_delete_routes', 'Can delete routes'), ('can_add_routes', 'Can add routes'), ('can_track_routes', 'Can track routes sent by themselves')]},
        ),
    ]
