# Generated by Django 5.2 on 2025-07-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0010_alter_route_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
    ]
