# Generated by Django 5.2 on 2025-08-06 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0011_alter_route_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='RouteColour',
            field=models.CharField(choices=[('IrnBru', 'Irn-Bru'), ('Flamingo', 'Flamingo'), ('Wasp', 'Wasp'), ('Mint', 'Mint'), ('Green', 'Green'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Red', 'Red'), ('Gryffindor', 'Gryffindor'), ('Pink', 'Pink'), ('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Grey', 'Grey'), ('Dalmatians', 'Dalmatians'), ('Blobs', 'Blobs')], default='IrnBru', max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteCreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 14, 49, 51, 121206)),
        ),
        migrations.AlterField(
            model_name='route',
            name='RouteGradeRange',
            field=models.CharField(choices=[('VB', 'VB'), ('V0_V2', 'V0-V2'), ('V1_V3', 'V1-V3'), ('V2_V4', 'V2-V4'), ('V3_V5', 'V3-V5'), ('V4_V6', 'V4-V6'), ('V5_V7', 'V5-V7'), ('V7plus', 'V7+'), ('OffCircuit', 'Off Circuit'), ('Comp', 'Comp')], default='VB', max_length=50),
        ),
    ]
