# Generated by Django 5.2 on 2025-08-06 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0012_alter_route_routecolour_alter_route_routecreatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='RouteCreatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
